### ISSUE TITLE
Blog posts aren't showing up

### ISSUE THREAD

**Issue by samanthasunne** [hackshackers/hackshackers-hugo-content#32]
I can see the last two newsletters in the /blog/ directory on Github but they don't show up on the public website.

@phillipadsmith @burtherman @joshkadis

**Comment by phillipadsmith** [comment]
Hey @joshkadis,

Wondering where the log files are written when Hugo tries to re-render the site? I'm wondering if this is an issue of an error that's preventing a re-render of the site?

Phillip.

**Comment by samanthasunne** [comment]
@phillipadsmith or @joshkadis any update on this? Announcing local grants soon and I'd really like to have the info on the site

**Comment by joshkadis** [comment]
Hi @samanthasunne and @phillipadsmith , I'm really sorry. The notifications for this ticket went into a mail folder that I don't check very often and I only received a notification from the deployment system for yesterday's failed deploy. There's some sort of issue with the deployment system that we're looking into. In the meantime, I'll get everything updated manually as soon as I can.
