### ISSUE TITLE
Raw HTML/JS appears (instead of Mailchimp signup form)

### ISSUE THREAD

**Issue by paulschreiber** [hackshackers/hackshackers-hugo-content#39]
https://hackshackers.com/blog/2012/02/subscribe-to-hackshackers-jobs-newsletter/

https://github.com/hackshackers/hackshackers-hugo-content/edit/master/blog/2012/02/subscribe-to-hackshackers-jobs-newsletter.md

![image](https://user-images.githubusercontent.com/86784/85155138-63bc2f00-b226-11ea-95a1-8632afd32786.png)

**Comment by samanthasunne** [comment]
Thanks for filing the issue, Paul! The post has been updated.

**Comment by paulschreiber** [comment]
Looks the same to me. Do I need to wait for a deploy?

**Comment by samanthasunne** [comment]
Yes, it can take a few hours to register. If you are looking for jobs
postings, those are now included on our general weekly newsletter:
https://hackshackers.us1.list-manage.com/subscribe/post?u=c56f2e53d5ed6ef87f8aaa75c&id=fb2bc6f10b

**Comment by paulschreiber** [comment]
Ah! I signed up for that. If there's no more jobs newsletter, can you update the post to indicate the newsletter no longer exists and folks should subscribe to the main one?
